# Generated by Django 3.2.20 on 2023-07-28 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_rename_time_zone_to_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='fetch_offset_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='If the fetch interval is 10 and the offset is 2, then data will be fetched at :02, :12, :22, etc. If the fetch interval is 1440 and the offset is 125, then data will be fetched every day at 02:05am. The offset generally counts from midnight.', validators=[django.core.validators.MaxValueValidator(1339)], verbose_name='Fetch time offset, in minutes'),
        ),
    ]
